/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redknot_mmplayer_MMPlayerJNI */

#ifndef _Included_com_redknot_mmplayer_MMPlayerJNI
#define _Included_com_redknot_mmplayer_MMPlayerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redknot_mmplayer_MMPlayerJNI
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_redknot_mmplayer_MMPlayerJNI_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
